app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
users:
    type:     rest
    resource: AppBundle\Controller\UsersController
    
groups:
    type:     rest
    resource: AppBundle\Controller\GroupsController
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
